name: notificare
description: Official Notificare Flutter plugin. Implements the power of the Notificare platform in Flutter applications.
version: 4.2.4
homepage: https://notificare.com
documentation: https://docs.notifica.re/sdk/v4/flutter/setup/
repository: https://github.com/Notificare/notificare-sdk-flutter/tree/main/notificare

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  notificare_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
